### ISSUE TITLE
Issues with Emoncms

### ISSUE THREAD

**Issue by UCLteam** [opendroplet/opendroplet-avr#1] opened 2015-03-10 12:08 UTC
We have built the sensor as explained in https://droplet.hackpad.com/Hardware-Primer-ZlAUIxXoOr8. You can find attached photographs of what we did:
![img_0630](https://cloud.githubusercontent.com/assets/11406900/6574978/38ab0b78-c722-11e4-9c3c-d71879922975.JPG)
![img_0631](https://cloud.githubusercontent.com/assets/11406900/6574983/43e5b6fa-c722-11e4-9e8d-7c7a901ed813.JPG)
![img_0632](https://cloud.githubusercontent.com/assets/11406900/6574984/479b0656-c722-11e4-9cf0-c2584f0ab6b0.JPG)
However we have a  few doubts:
- the thickness of the antenna connected to the sensor (it was not precised in the protocol) 
- the connection between VCC of the microphone to the Moteino: we chose finally 3V3. Is there some new code to add to the OpenDropletOEM file?

We have loaded the OpenDropletOEM file to the sensor, without doing any changes.

We have connected the rfm12pi to the rpibasestation b+ but we are not sure which pins we should use exactly. You can find attach the photograph of what we did:
![img_0629](https://cloud.githubusercontent.com/assets/11406900/6574968/1e54afae-c722-11e4-95b7-08317b78d8f8.JPG)

We have loaded the ready-to-go SD card image to the SD card as explained in steps 1 and 2 of https://github.com/emoncms/emoncms/blob/bufferedwrite/docs/setup.md

We have configured the basestation to store locally the data as explained in step 3a) of https://github.com/emoncms/emoncms/blob/bufferedwrite/docs/setup.md. 
Here is our emonhub.conf file:
![1](https://cloud.githubusercontent.com/assets/11406900/6575668/c5433f14-c728-11e4-96c8-1c4d1dcc425a.jpg)
![2](https://cloud.githubusercontent.com/assets/11406900/6575678/d3603836-c728-11e4-9085-56c7a3b767f8.jpg)

However, we are not sure of the group and the baseid of the RFM12pi module: we left the initial values: group=210, baseid=15. The frequence is 433MHz.

Now, "inputs should start appearing in the inputs section of your emoncms account". It worked once: ![screenshot of inputs](https://cloud.githubusercontent.com/assets/11406900/6574684/0b50650e-c71f-11e4-9c98-5ca0c9b24b57.png). Is this what we are expecting? 
There were 3 inputs appearing : Node 1 - key 1, Node 1 - key 2, Node 1 -key 3. 
However, these inputs just disappear and we can no longer see them. Shure proposed to:
-"checked that the rpi filesystem is read AND write enable after reboot": however in https://github.com/emoncms/emoncms/blob/bufferedwrite/docs/setup.md they say to "Set the raspberrypi os back into read-only mode" at the end of the protocol, before checking the inputs
-"checked serial output from sensor": what does this mean exactly?
-"rfm hub service on rpi running": yes, this is the case.

When we connect the power of the basestation, connected to a screen, there are three strange texts: 
![basestation shrinked](https://cloud.githubusercontent.com/assets/11406900/6575103/6efb0286-c723-11e4-95b3-5b3f41aa15fb.jpg)
The log is said to be off but in the file: boot/emonhub.conf, loglevel = WARNING

When we write the "sudo iostat 60" command, kb_wrtn/s is not as it should be (around 0.5-1.5 kb_wrtn/s):
![sans titre](https://cloud.githubusercontent.com/assets/11406900/6575322/aff9c3a6-c725-11e4-8063-1a276611c148.jpg)

Some mistakes can come from any of the previous steps. However, as we saw the inputs once, can't we assume that no mistakes were made? Except if it is possible that the inputs seen are coming from another RFM12 device?

**Comment by shulter** [comment] 2015-03-10 14:15
I will try to address your questions:

> However, as we saw the inputs once, can't we assume that no mistakes were made? Except if it is possible that the inputs seen are coming from another RFM12 device?
> The data you saw seems to be your node, the array of three data points absolutely correlates with the data you send from the node.
> 
> When we write the "sudo iostat 60" command, kb_wrtn/s is not as it should be (around 0.5-1.5 kb_wrtn/s)

I can't follow your problem there, the system seems to work well - it would be broken if it would show anything above 0, because you put it into read only mode immediately before. Why should the write stat be around 0.5-1.5 kb/s, when nothing is allowed to write to the sd card? 

I would not put the system into a read only state as you want to tweak files and log data. The error messages at bootup seem to be normal due to the read only state. It does not start in read and write state to reduce wear on the filesystem due to the nature of SD cards, they have a limited amount of writing operations, but a near unlimited amount of read operations before they will fail.

The error which says

> Starting redis server: failed.

could be a problem, as redis seems essential to buffer the incoming data. However, the error could be coming up because the service is already up and running, thus can't be started a second time. If you are not familiar with the linux shell and the evaluation of running processes, I guess the following commands are an easy approach to see if the redis service has been running:

```
sudo service redis-server start
sudo service redis-server stop
sudo service redis-server restart
```

The antenna length should be 165 mm for the rfm12b frequency of 433 Mhz. The wire width is unimportant.

The batteries you are using don't look healthy at all. I assume they are rechargeable batteries and have been damaged with overcharging and thus overheating. If any of the batteries touch their adjacent battery due to the broken insulation they will form a short circuit.  

I suggest you connect the Moteino to your computer and look at the serial output, for example with the Arduino IDE.

**Comment by UCLteam** [comment] 2015-03-10 15:33
We tried what you proposed (we put the write mode, the service you talked about was indeed already running, the antenna is 165mm long and we use the USB adapter to power the sensor) but it still does not work.

We are now building another sensor to try evrything again on the new sensor to see if there is anything wrong with soldering.

**Comment by UCLteam** [comment] 2015-03-10 18:54
We tried what you proposed (we put the write mode, the service you talked about was indeed already running, the antenna is 165mm long and we use the USB adapter to power the sensor) but it still does not work.

We don't know what you mean by "serial output". What is it and where can we find it with the Arduino IDE? What the serial output should look like?

We are now building another sensor to try evrything again on the new sensor to see if there is anything wrong with soldering.

**Comment by UCLteam** [comment] 2015-03-10 18:57
With the first sensor:
- the orange LED of the sensor is constant
- the green light of the rfm12pi near the antenna is off

With the new sensor we have just built:
- the orange LED of the sensor is flashing
- the green light near the antenna of the rfm12pi (connected to the basestation) is flashing when the sensor is on

What is expected with these two LED theoretically (we assume that these 2 sensors behave differently because of component issues)? Fom the code on the sensor, it seems that the orange LED of the sensor should be flashing. However inputs are still not appearing on emoncms with the new sensor.

Here is our serial ouput with the new sensor
![serial outpu](https://cloud.githubusercontent.com/assets/11406900/6594851/b47ba356-c7dc-11e4-98c6-fc2bfc2d4e67.jpg)
Therefore the new sensor seems to record well sounds. Could you explain what "emontx.spl" and emontx.vbat" represent? Are they supposed to be equal to 0?

**Comment by jmatsushita** [comment] 2015-03-11 13:44
Hi,

The new sensor seems to exhibit the correct behavior which is flashing everytime a packet is sent via rfm12. Now I have pushed a change so that:
- Now the LED is brighter when the sound received is louder and dimmer when it is quiter. This should help to calibrate the microphone gain (with the very small potentiometer at the back of the microphone. Be very careful as it is fragile)
- A bug where the emontx.spl variable wasn't set is fixed.

Please upload the new code (run `git pull`to get the new code, and use the Arduino IDE to push it) and let us know if that changes anything on EmonCMS.

**Comment by jmatsushita** [comment] 2015-03-11 15:52
@UCLTeam  Can you also try on the hub:
- Setting the loglevel at INFO
- Restart emonhub : `sudo service emonhub restart`
- Posting here a few dozen lines of the emonhub log : `tail -f /var/log/emonhub/emonhub.log`

**Comment by UCLteam** [comment] 2015-03-11 16:20
we tried what you suggested, we checked the emonhub log, but there is a line saying WARNING as shown by the print screen attached:
![tail](https://cloud.githubusercontent.com/assets/11406900/6600926/66d43eaa-c80a-11e4-8c7a-f5a2b5ee744e.jpg)
This is our emonhub.conf file now:
![aaa](https://cloud.githubusercontent.com/assets/11406900/6601205/38ab573c-c80c-11e4-8dc5-ea2150063e30.jpg)
![bbb](https://cloud.githubusercontent.com/assets/11406900/6601211/3fe9a558-c80c-11e4-8db3-74929ccdf565.jpg)
The new seral output looks like this:
![serial output](https://cloud.githubusercontent.com/assets/11406900/6601456/b0234d00-c80d-11e4-955d-f5fa8f4792d3.jpg)

**Comment by jmatsushita** [comment] 2015-03-11 16:25
@UCLteam Can you paste (instead of screenshots) here the result of `sudo ps faux`

**Comment by jmatsushita** [comment] 2015-03-11 16:29
@UCLteam Also please do the following:
- `sudo service emonhub stop`
- Then (with the Pi still powered) physically remove the RFM12b board from the Raspberry Pi GPIO pins.
- Re-insert the RFM12b board on the RPi.
- `sudo service emonhub start`
- Post the result of `tail -f /var/log/emonhub/emonhub.log` again.

**Comment by UCLteam** [comment] 2015-03-11 16:50
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    16:00   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [ksoftirqd/0]
root         5  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [kworker/0:0H]
root         6  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [kworker/u2:0]
root         7  0.1  0.0      0     0 ?        S    16:00   0:03  \_ [rcu_preempt]
root         8  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [rcu_sched]
root         9  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [rcu_bh]
root        10  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [khelper]
root        11  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [kdevtmpfs]
root        12  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [netns]
root        13  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [perf]
root        14  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [khungtaskd]
root        15  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [writeback]
root        16  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [crypto]
root        17  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [bioset]
root        18  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [kblockd]
root        19  0.1  0.0      0     0 ?        S    16:00   0:03  \_ [kworker/0:1]
root        20  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [rpciod]
root        21  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [kswapd0]
root        22  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [fsnotify_mark]
root        23  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [nfsiod]
root        29  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [kthrotld]
root        30  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [VCHIQ-0]
root        31  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [VCHIQr-0]
root        32  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [VCHIQs-0]
root        33  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [iscsi_eh]
root        34  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [dwc_otg]
root        35  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [DWC Notificatio]
root        37  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [VCHIQka-0]
root        38  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [SMIO]
root        39  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [deferwq]
root        41  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [mmcqd/0]
root        42  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [jbd2/mmcblk0p2-]
root        43  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [ext4-rsv-conver]
root        44  0.0  0.0      0     0 ?        S    16:00   0:00  \_ [kworker/0:2]
root      1132  0.0  0.0      0     0 ?        S<   16:00   0:00  \_ [ext4-rsv-conver]
root      2907  0.0  0.0      0     0 ?        S    16:07   0:00  \_ [kworker/u2:1]
root         1  0.0  0.2   2152  1320 ?        Ss   16:00   0:00 init [2]
root       159  0.0  0.4   2892  2164 ?        Ss   16:00   0:00 udevd --daemon
root       295  0.0  0.4   2888  1912 ?        S    16:00   0:00  \_ udevd --daemon
root       303  0.0  0.4   2888  1912 ?        S    16:00   0:00  \_ udevd --daemon
root      1494  0.0  0.2   1756  1152 ?        S    16:00   0:00 /usr/sbin/ifplugd -i lo -q -f -u0 -d10 -w -I
root      1535  0.0  0.2   1756  1224 ?        S    16:00   0:02 /usr/sbin/ifplugd -i eth0 -q -f -u0 -d10 -w -I
root      1792  0.0  0.8   4904  3596 ?        Ss   16:00   0:00 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
root      1823  0.0  0.5  27996  2476 ?        Sl   16:00   0:00 /usr/sbin/rsyslogd -c5
nobody    1854  0.0  0.3   2024  1476 ?        Ss   16:00   0:00 /usr/sbin/thd --daemon --triggers /etc/triggerhappy/triggers.d/ --socket /var/run/thd.socket --pidfile
root      1874  0.0  3.3  39432 15016 ?        Ss   16:00   0:00 /usr/sbin/apache2 -k start
www-data  1935  0.3  2.8  41980 12520 ?        S    16:00   0:10  \_ /usr/sbin/apache2 -k start
www-data  1936  0.4  2.8  42200 12700 ?        S    16:00   0:12  \_ /usr/sbin/apache2 -k start
www-data  2913  0.4  2.8  42200 12684 ?        S    16:07   0:10  \_ /usr/sbin/apache2 -k start
www-data  2915  0.4  2.8  42200 12804 ?        S    16:07   0:12  \_ /usr/sbin/apache2 -k start
www-data  2927  0.4  2.6  41352 11700 ?        S    16:08   0:09  \_ /usr/sbin/apache2 -k start
www-data  2939  0.4  2.8  41956 12532 ?        S    16:09   0:10  \_ /usr/sbin/apache2 -k start
www-data  2948  0.4  2.8  41956 12528 ?        S    16:10   0:10  \_ /usr/sbin/apache2 -k start
www-data  3179  0.4  2.8  42132 12632 ?        S    16:25   0:05  \_ /usr/sbin/apache2 -k start
www-data  3202  0.3  2.7  41868 12140 ?        S    16:33   0:03  \_ /usr/sbin/apache2 -k start
www-data  3218  0.3  2.6  41352 11688 ?        S    16:45   0:00  \_ /usr/sbin/apache2 -k start
root      1932  0.0  0.4   3832  1920 ?        Ss   16:00   0:00 /usr/sbin/cron
104       1940  0.0  0.3   3184  1512 ?        Ss   16:00   0:00 /usr/bin/dbus-daemon --system
109       2047  0.0  0.3   2288  1672 ?        S    16:00   0:00 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
root      2101  0.0  0.2   1764  1160 ?        S    16:00   0:00 /bin/sh /usr/bin/mysqld_safe
mysql     2442  0.5  8.5 324792 38088 ?        Sl   16:00   0:16  \_ /usr/sbin/mysqld --basedir=/usr --datadir=/home/pi/data/mysql --plugin-dir=/usr/lib/mysql/plugin --
root      2443  0.0  0.3   1856  1368 ?        S    16:00   0:00  \_ logger -t mysqld -p daemon.error
root      2465  0.0  3.1  36104 14192 ?        S    16:00   0:00 /usr/bin/php -f /var/www/emoncms/run/feedwriter.php
ntp       2490  0.0  0.7   5524  3228 ?        Ss   16:00   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 102:104
redis     2534  0.2  0.5  27364  2320 ?        Ssl  16:00   0:06 /usr/bin/redis-server /etc/redis/redis.conf
root      2561  0.0  0.6   6224  2948 ?        Ss   16:00   0:00 /usr/sbin/sshd
root      3182  0.0  0.9   9268  4448 ?        Ss   16:28   0:00  \_ sshd: pi [priv]
pi        3186  0.0  0.8   9268  3580 ?        S    16:28   0:00      \_ sshd: pi@pts/1
pi        3187  0.1  1.0   6252  4492 pts/1    Ss   16:28   0:01          \_ -bash
root      3221  0.0  0.5   4592  2632 pts/1    S+   16:49   0:00              \_ sudo ps faux
root      3222  0.0  0.4   4460  2188 pts/1    R+   16:49   0:00                  \_ ps faux
root      2646  0.0  0.4   3268  2096 tty1     Ss   16:00   0:00 /bin/login -f      tty1
root      2656  0.0  0.9   5652  4112 tty1     S+   16:00   0:00  \_ -bash
root      2647  0.0  0.3   3752  1704 tty2     Ss+  16:00   0:00 /sbin/getty 38400 tty2
root      2648  0.0  0.3   3752  1708 tty3     Ss+  16:00   0:00 /sbin/getty 38400 tty3
root      2649  0.0  0.3   3752  1748 tty4     Ss+  16:00   0:00 /sbin/getty 38400 tty4
root      2650  0.0  0.3   3752  1648 tty5     Ss+  16:00   0:00 /sbin/getty 38400 tty5
root      2651  0.0  0.3   3752  1636 tty6     Ss+  16:00   0:00 /sbin/getty 38400 tty6
emonhub   2976  7.6  2.4  22304 11068 ?        Sl   16:12   2:47 python /usr/share/emonhub/emonhub.py --logfile /var/log/emonhub/emonhub.log --config-file /etc/emonhub/
pi@emonbase ~ $
```

**Comment by jmatsushita** [comment] 2015-03-11 16:54
Please use the triple backquote notation (before and after) to make such pasted logs more readable. that is three of those: ` 

I've edited your previous post to include this.

**Comment by UCLteam** [comment] 2015-03-11 17:00
The new result:

```
2015-03-11 16:59:01,488 INFO Creating EmonHubEmoncmsReporter 'emonCMS'
2015-03-11 16:59:01,493 INFO Set up reporter 'emonCMS' (buffer: memory | size: 1000)
2015-03-11 16:59:01,497 INFO Setting emonCMS url: http://localhost/emoncms
2015-03-11 16:59:01,500 INFO Setting emonCMS apikey: set
2015-03-11 16:59:01,502 INFO Creating EmonHubJeeInterfacer 'RFM2Pi'
2015-03-11 16:59:05,541 WARNING Device communication error - check settings
2015-03-11 16:59:05,544 INFO Setting RFM2Pi frequency: 433 (4b)
2015-03-11 16:59:06,547 INFO Setting RFM2Pi group: 210 (210g)
2015-03-11 16:59:07,551 INFO Setting RFM2Pi quiet: 1 (1q)
2015-03-11 16:59:08,554 INFO Setting RFM2Pi baseid: 15 (15i)
```

**Comment by jmatsushita** [comment] 2015-03-11 17:14
(it's backquotes ` rather than simple quotes ').

Is the sensor powered on? When you power it on, do you see the LED on the RFM12b board on the RPi blink?

**Comment by UCLteam** [comment] 2015-03-11 17:16
yes the sensor is powered on
yes the LED on the RFM12B is blinking

**Comment by UCLteam** [comment] 2015-03-11 17:18
Could we please have a skype call? It might be easier.

**Comment by jmatsushita** [comment] 2015-03-11 17:19
But then it would only help you instead of potential future people having similar problems!

**Comment by jmatsushita** [comment] 2015-03-11 17:21
So this line:
`2015-03-11 16:59:05,541 WARNING Device communication error - check settings`

is the problem. It means that the RPi cannot talk to the RFM12B board. The way the RPi system should talk to it is via the /dev/ttyAMA0 device which is a serial port.

Can you increase the LogLevel to debug and post the log again?

**Comment by UCLteam** [comment] 2015-03-11 17:25
```
2015-03-11 16:59:01,493 INFO Set up reporter 'emonCMS' (buffer: memory | size: 1                                                                                        000)
2015-03-11 16:59:01,497 INFO Setting emonCMS url: http://localhost/emoncms
2015-03-11 16:59:01,500 INFO Setting emonCMS apikey: set
2015-03-11 16:59:01,502 INFO Creating EmonHubJeeInterfacer 'RFM2Pi'
2015-03-11 16:59:05,541 WARNING Device communication error - check settings
2015-03-11 16:59:05,544 INFO Setting RFM2Pi frequency: 433 (4b)
2015-03-11 16:59:06,547 INFO Setting RFM2Pi group: 210 (210g)
2015-03-11 16:59:07,551 INFO Setting RFM2Pi quiet: 1 (1q)
2015-03-11 16:59:08,554 INFO Setting RFM2Pi baseid: 15 (15i)
2015-03-11 17:22:30,199 INFO Logging level set to DEBUG
```

**Comment by jmatsushita** [comment] 2015-03-11 17:26
You need to restart the emonhub service to reload the new configuration.

**Comment by UCLteam** [comment] 2015-03-11 17:28
```
2015-03-11 17:27:10,011 INFO Exit completed
2015-03-11 17:27:11,738 INFO EmonHub Pre-Release Development Version (rc1.2)
2015-03-11 17:27:11,740 INFO Opening hub...
2015-03-11 17:27:11,743 INFO Logging level set to DEBUG
2015-03-11 17:27:11,746 INFO Creating EmonHubEmoncmsReporter 'emonCMS'
2015-03-11 17:27:11,751 INFO Set up reporter 'emonCMS' (buffer: memory | size: 1000)
2015-03-11 17:27:11,755 INFO Setting emonCMS url: http://localhost/emoncms
2015-03-11 17:27:11,757 INFO Setting emonCMS apikey: set
2015-03-11 17:27:11,762 INFO Creating EmonHubJeeInterfacer 'RFM2Pi'
2015-03-11 17:27:11,767 DEBUG Opening serial port: /dev/ttyAMA0 @ 38400 bits/s
2015-03-11 17:27:15,794 WARNING Device communication error - check settings
2015-03-11 17:27:15,798 INFO Setting RFM2Pi frequency: 433 (4b)
2015-03-11 17:27:16,803 INFO Setting RFM2Pi group: 210 (210g)
2015-03-11 17:27:17,809 INFO Setting RFM2Pi quiet: 1 (1q)
2015-03-11 17:27:18,814 INFO Setting RFM2Pi baseid: 15 (15i)
```

**Comment by jmatsushita** [comment] 2015-03-11 17:32
I'm looking into it here: http://openenergymonitor.org/emon/node/6244 and here https://github.com/emonhub/emonhub/issues/58#issuecomment-66480108

May I suggest you do the same please?

**Comment by UCLteam** [comment] 2015-03-11 17:35
We are reading it

**Comment by jmatsushita** [comment] 2015-03-11 17:35
@UCLteam can you try `minicom -b9600 -D/dev/ttyAMA0` (note that to exit minicom you need to first press CTRL together with the A letter, then the X key, finally press Enter to select 'Yes').

**Comment by UCLteam** [comment] 2015-03-11 17:41
```
8 42 0 164 0 0 0
 8 42 0 159 1 0 0
 8 42 0 159 0 0 0
 8 42 0 89 1 0 0
 8 42 0 86 1 0 0
 8 42 0 149 0 0 0
 8 42 0 145 0 0 0
 8 42 0 160 0 0 0
 8 42 0 19 1 0 0
 8 42 0 154 0 0 0
 8 42 0 44 1 0 0
 8 42 0 172 0 0 0
```

**Comment by jmatsushita** [comment] 2015-03-11 17:44
Ok that's good! So the problem is that the speed of the serial port is not detected properly. You should be able to work around that by adding the **com_baud = 9600** line to your emonhub.conf and restarting emonhub.

```
[[RFM2Pi]]
    Type = EmonHubJeeInterfacer
    [[[init_settings]]]
        com_port = /dev/ttyAMA0
        com_baud = 9600
    [[[runtimesettings]]]
        group = 210
        frequency = 433
        baseid = 15
```

**Comment by jmatsushita** [comment] 2015-03-11 17:47
@UCLteam Then as I suspect it will work, don't forget to get back to the `WARNING` LogLevel so that the SD card doesn't overfill.

**Comment by UCLteam** [comment] 2015-03-11 17:50
Yes, it works!!!

**Comment by UCLteam** [comment] 2015-03-11 18:18
Thank you very much for the help!!! Now, we see inputs and on the three inputs nodes, the value of node 1 is 42 which we thought is the the uid of the sensor (because in the code and the serial output we saw the value of 42 correspond to uid). The value of node 2 is changing and we think this value correspond to the peaktopeak in the serial output. And the third node is 0. We are wondering what the value of node 2 represents? What is the unit of the value?

**Comment by jmatsushita** [comment] 2015-03-12 09:16
I'll close this issue, please now open one issue per problem or question. Thanks!.

**Closed as completed by jmatsushita** 2015-03-12 09:16 UTC

**Comment by pb66** [comment] 2015-03-13 18:19
I know this issue is closed already but some info maybe useful (better late than never!) sorry  I wasn't around yesterday. 

"_The log is said to be off but in the file: boot/emonhub.conf, loglevel = WARNING_" You have several things going on at once causing overlaps in the log messages, the "Log is turned off" is not related to emonhub. It is a message from emoncms's feedwriter daemon. The previous "red boxed" message about swap files could (should?) be handled better and configured off rather than "failed" the end result is no swap files due to be read-only. The nature of emoncms data would damage the sd card if not read-only so "expanding the memory" using swap files isn't recommended and probally not needed as an emonBase doesn't do too much memory intensive stuff.

There is a known occasional issue with emonhub auto baud detection which is discussed in more detail on the emonhub repo, it can be easily overridden using the "com_baud" setting as you have. It is normally occasional and the fact you saw it quite frequently makes me suspect you have something else accesing the serial port, since emonhub will only NOT move on to the next baud to try if it gets a legible response, hence the "occasional" stray data in a buffer causing emonhub to think it's got a resonse, for it to happen so consistently makes me wonder if it's picking up something elses data.

"_don't forget to get back to the WARNING LogLevel so that the SD card doesn't overfill._" emonhub.log is written to RAM on the read-only image plus it is limited to a max of 2 5MB files in rotation.

Paul
